package com.lollipop.tamagotchi.domain.engine

import java.util.Random

/**
 * 宝可梦游戏中出现过的地名（doc 任务：离线结算时宠物「去外面玩」的目的地池）。
 *
 * - [en] 为主键（稳定、与地区官方英文名一致）；[zh] 为官方/通用中文译名，缺失则回退 [en]。
 * - 列表足量、彼此去重，避免离线回放里反复撞同一地名。
 * - 离线时间线在「离线够久」时才可能抽中一个目的地（见 [DefaultOfflineTimelineBuilder.insertOuting]）。
 */
data class Place(
    val en: String,
    val zh: String?,
)

object PokemonPlaces {

    private val PLACES: List<Place> = listOf(
        // ── Kanto ──
        Place("Pallet Town", "真新镇"),
        Place("Viridian City", "常磐市"),
        Place("Pewter City", "尼比市"),
        Place("Cerulean City", "华蓝市"),
        Place("Vermilion City", "枯叶市"),
        Place("Lavender Town", "紫苑镇"),
        Place("Celadon City", "彩虹市"),
        Place("Fuchsia City", "浅红市"),
        Place("Saffron City", "金黄市"),
        Place("Cinnabar Island", "红莲岛"),
        Place("Indigo Plateau", "石英高原"),
        Place("Viridian Forest", "常磐森林"),
        Place("Mt. Moon", "月见山"),
        Place("Rock Tunnel", "岩山隧道"),
        Place("Victory Road", "冠军之路"),
        Place("Pokémon Tower", "宝可梦塔"),
        Place("Seafoam Islands", "双子岛"),
        Place("Kanto Power Plant", "枯叶市发电站"),
        Place("Pokémon Mansion", "宝可梦豪宅"),
        Place("Saffron Dojo", "金黄道场"),
        // ── Johto ──
        Place("New Bark Town", "若叶镇"),
        Place("Cherrygrove City", "桔梗镇"),
        Place("Violet City", "桧皮镇"),
        Place("Azalea Town", "圆朱镇"),
        Place("Cianwood City", "湛蓝市"),
        Place("Olivine City", "浅黄市"),
        Place("Mahogany Town", "桃源镇"),
        Place("Blackthorn City", "黑金市"),
        Place("Goldenrod City", "满金市"),
        Place("Ecruteak City", "缘朱市"),
        Place("Whirl Islands", "漩涡岛"),
        Place("Mt. Silver", "白银山"),
        Place("Dark Cave", "黑暗洞"),
        Place("Ruins of Alph", "阿露福遗迹"),
        Place("Dragon's Den", "龙穴"),
        Place("Lake of Rage", "愤怒之湖"),
        // ── Hoenn ──
        Place("Littleroot Town", "未白镇"),
        Place("Oldale Town", "古辰镇"),
        Place("Petalburg City", "橙华市"),
        Place("Rustboro City", "卡那兹市"),
        Place("Dewford Town", "武斗镇"),
        Place("Slateport City", "凯那市"),
        Place("Mauville City", "紫堇市"),
        Place("Verdanturf Town", "绿荫镇"),
        Place("Fallarbor Town", "釜炎镇"),
        Place("Lavaridge Town", "焰岩镇"),
        Place("Fortree City", "绿茵镇"),
        Place("Lilycove City", "绿岭市"),
        Place("Mossdeep City", "绿岭市"),
        Place("Sootopolis City", "琉璃市"),
        Place("Pacifidlog Town", "武藏镇"),
        Place("Ever Grande City", "彩幽市"),
        Place("Mt. Chimney", "烟囱山"),
        Place("Meteor Falls", "流星瀑布"),
        Place("Fiery Path", "火焰小径"),
        Place("Seafloor Cavern", "海底洞窟"),
        Place("Sky Pillar", "天空之柱"),
        Place("Cave of Origin", "觉醒神殿"),
        Place("Petalburg Woods", "橙华森林"),
        Place("Route 101", "101号道路"),
        Place("Route 119", "119号道路"),
        // ── Sinnoh ──
        Place("Twinleaf Town", "双叶镇"),
        Place("Sandgem Town", "真砂镇"),
        Place("Jubilife City", "祝庆市"),
        Place("Oreburgh City", "黑金市"),
        Place("Eterna City", "苑之镇"),
        Place("Hearthome City", "家缘市"),
        Place("Veilstone City", "帷幕市"),
        Place("Pastoria City", "野原市"),
        Place("Canalave City", "水脉市"),
        Place("Snowpoint City", "雪峰市"),
        Place("Sunyshore City", "名木市"),
        Place("Fight Area", "战斗区"),
        Place("Resort Area", "度假区"),
        Place("Mt. Coronet", "天冠山"),
        Place("Lake Verity", "心齐湖"),
        Place("Lake Valor", "英知湖"),
        Place("Lake Acuity", "立志湖"),
        Place("Stark Mountain", "烈焰火山"),
        Place("Snowpoint Temple", "雪峰神殿"),
        Place("Fullmoon Island", "满月的岛"),
        Place("Newmoon Island", "新月的岛"),
        // ── Unova ──
        Place("Nuvema Town", "鹿子镇"),
        Place("Accumula Town", "唐草镇"),
        Place("Striaton City", "三曜市"),
        Place("Nacrene City", "七宝市"),
        Place("Castelia City", "飞云市"),
        Place("Nimbasa City", "雷文市"),
        Place("Driftveil City", "帆巴市"),
        Place("Mistralton City", "吹寄市"),
        Place("Icirrus City", "雪花市"),
        Place("Opelucid City", "双龙市"),
        Place("Lacunosa Town", "笼目镇"),
        Place("Humilau City", "涟漪镇"),
        Place("Undella Town", "细波镇"),
        Place("Black City", "黑色市"),
        Place("White Forest", "白色森林"),
        Place("Giant Chasm", "巨大洞穴"),
        Place("Dragonspiral Tower", "螺旋塔"),
        Place("Relic Castle", "古代城堡"),
        Place("Pinwheel Forest", "旋转森林"),
        Place("Chargestone Cave", "充电石洞穴"),
        Place("Twist Mountain", "扭转石窟"),
        Place("Reversal Mountain", "逆转山"),
        Place("Moor of Icirrus", "雪花湿地"),
        Place("Victory Road", "冠军之路"),
        // ── Kalos ──
        Place("Vaniville Town", "范莲町"),
        Place("Santalune City", "白檀市"),
        Place("Lumiose City", "密阿雷市"),
        Place("Camphrier Town", "旅宿镇"),
        Place("Cyllage City", "遥香市"),
        Place("Shalour City", "娑罗市"),
        Place("Couriway Town", "比翼镇"),
        Place("Geosenge Town", "石香镇"),
        Place("Kiloude City", "弥藩市"),
        Place("Ambrette Town", "海翼镇"),
        Place("Anistar City", "麻芽镇"),
        Place("Laverre City", "冰里市"),
        Place("Dendemille Town", "百刻市"),
        Place("Snowbelle City", "雪风镇"),
        Place("Terminus Cave", "终结洞窟"),
        Place("Frost Cavern", "冰晶洞窟"),
        Place("Lost Hotel", "迷失旅馆"),
        Place("Sea Spirit's Den", "海神之穴"),
        Place("Pokémon Village", "宝可梦村庄"),
        // ── Alola ──
        Place("Hau'oli City", "好奥乐市"),
        Place("Iki Town", "好奥乐镇"),
        Place("Heahea City", "慷待市"),
        Place("Paniola Town", "欧哈纳镇"),
        Place("Konikoni City", "卡拉蔚市"),
        Place("Royal Avenue", "皇家大道"),
        Place("Malie City", "玛奥拉市"),
        Place("Tapu Village", "守护神村"),
        Place("Po Town", "毒贝塔镇"),
        Place("Melemele Meadow", "美乐美乐草原"),
        Place("Brooklet Hill", "潺潺之丘"),
        Place("Wela Volcano Park", "维拉火山公园"),
        Place("Lush Jungle", "树丛林"),
        Place("Mount Lanakila", "拉纳基拉山"),
        Place("Aether Paradise", "以太乐园"),
        Place("Exeggutor Island", "椰蛋树岛"),
        Place("Poni Wilds", "波尼原野"),
        Place("Vast Poni Canyon", "波尼大峡谷"),
        Place("Altar of the Sunne", "日轮祭坛"),
        Place("Altar of the Moone", "月轮祭坛"),
        Place("Ruins of Conflict", "争斗遗迹"),
        // ── Galar ──
        Place("Postwick", "木杆镇"),
        Place("Wedgehurst", "楔石镇"),
        Place("Turffield", "圆阵镇"),
        Place("Hulbury", "水舟镇"),
        Place("Motostoke", "机擎市"),
        Place("Hammerlocke", "拳关市"),
        Place("Circhester", "溯传镇"),
        Place("Spikemuth", "尖钉镇"),
        Place("Ballonlea", "舞姿镇"),
        Place("Wyndon", "宫门市"),
        Place("Stow-on-Side", "藏玛镇"),
        Place("Wild Area", "旷野地带"),
        Place("Galar Mine", "伽勒尔矿山"),
        Place("Dusty Bowl", "尘泥洼地"),
        Place("Giant's Cap", "巨人帽岩"),
        Place("Lake of Outrage", "愤怒湖"),
        Place("Isle of Armor", "铠之孤岛"),
        Place("Crown Tundra", "王冠雪原"),
        Place("Freezington", "冻凝村"),
        // ── Paldea ──
        Place("Cabo Poco", null),
        Place("Mesagoza", "蜜原市"),
        Place("Levincia", "莱文奇亚市"),
        Place("Cascarrafa", "喀斯喀拉法"),
        Place("Porto Marinada", "马利纳达港"),
        Place("Medali", "梅德里"),
        Place("Montenevera", "蒙特内维拉"),
        Place("Alfornada", "阿尔福雷达"),
        Place("Cortondo", "科尔东多"),
        Place("Artazon", "阿尔萨宗"),
        Place("Glaseado Mountain", "格拉雪多山"),
        Place("Asado Desert", "阿斯阿多沙漠"),
        Place("South Province", "南帕底亚"),
        Place("East Province", "东帕底亚"),
        Place("West Province", "西帕底亚"),
        Place("North Province", "北帕底亚"),
        Place("Area Zero", "零区"),
        Place("Poco Path", "Poco 小径"),
        Place("Inlet Grotto", "入江洞窟"),
    )

    /** 从目的地池随机抽一个（离线时间线用）。 */
    fun pick(rng: Random): Place = PLACES[rng.nextInt(PLACES.size)]

    /** 按语言取目的地名；未收录中文时回退英文。 */
    fun localized(enKey: String, zh: Boolean): String {
        val p = PLACES.firstOrNull { it.en == enKey } ?: return enKey
        return if (zh) p.zh ?: p.en else p.en
    }
}
