package com.lollipop.grokbot.internal

/**
 * One body silhouette plus the face placement that belongs to it.
 *
 * Hand written on purpose: [GrokGeometryData] is generated by `temp/gen-geometry.mjs`,
 * so the constructor order here must stay in sync with that generator:
 *
 * `id, label, path, face.x, face.y, face.sx, face.sy, face.eye, radius, tiltScale, top, bottom`
 *
 * Plain class (not a data class) so that the very large [path] string never leaks into
 * `toString()` output.
 */
internal class GrokShapeData(
    /** Stable identifier shared with the web build, e.g. `"blob"`. */
    val id: String,
    /** Human readable name, e.g. `"Blob"`. */
    val label: String,
    /** Raw SVG path of the body outline, in the 229x229 design space. */
    val path: String,
    /** Face plate X offset. */
    val faceX: Float,
    /** Face plate Y offset. */
    val faceY: Float,
    /** Face plate horizontal scale. */
    val faceSx: Float,
    /** Face plate vertical scale. */
    val faceSy: Float,
    /** Eye aperture multiplier for this body. */
    val faceEye: Float,
    /** Bounding radius used by the overlay ring maths. */
    val radius: Float,
    /** How much the 3D turn trick is scaled for this body. */
    val tiltScale: Float,
    /** Top silhouette sample used for badge placement. */
    val top: Float,
    /** Bottom silhouette sample used by the eye pass. */
    val bottom: Float,
) {

    /** Face placement packaged for the eye pass, mirrors `geo.shapes[id].face`. */
    val face: GrokBot = GrokBot(faceX, faceY, faceSx, faceSy, faceEye)

    /**
     * A fresh face instance. The web build spreads `{...shape.face}` before mutating it,
     * so the engine must never write into [face] directly; use this instead.
     */
    fun newFace(): GrokBot = GrokBot(faceX, faceY, faceSx, faceSy, faceEye)
}

/**
 * Two stop colours of the body gradient: [light] on the upper left, [dark] on the lower right.
 * Values are `#RRGGBB` strings, resolved to Compose colours by the renderer.
 */
internal class GrokPaletteData(
    val light: String,
    val dark: String,
)
